# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Trazabilidad' do
  
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'SwiftyJSON'


  target 'TrazabilidadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TrazabilidadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
